
-- PROGRESSION 1:

--1. Insert into city
SELECT * FROM CITY;
INSERT INTO CITY(ID,NAME)VALUES(12341,'SNEHA');
INSERT INTO CITY(ID,NAME)VALUES(12357,'LATHA')


--2. Insert into referee
SELECT * FROM REFEREE;
INSERT INTO REFEREE(ID,NAME)VALUES(12342,'SATISH');

--3. Insert into innings
SELECT * FROM INNINGS;
INSERT INTO INNINGS(ID,INNINGS_NUMBER)VALUES(12343,12344);

--4. Insert into extra_type
SELECT * FROM EXTRA_TYPE;
INSERT INTO EXTRA_TYPE(ID,NAME)VALUES(12345,'RAHUL SINGH');

--5. Insert into skill
SELECT * FROM SKILL;
INSERT INTO SKILL(ID,NAME)VALUES(12346,'ROHAN PATIL');
INSERT INTO SKILL(ID,NAME)VALUES(12358,'MS FAZEL')
INSERT INTO SKILL(ID,NAME)VALUES(11,'ALL ROUNDER');
INSERT INTO SKILL(ID,NAME)VALUES(12,'BATTING');
INSERT INTO SKILL(ID,NAME)VALUES(13,'BOWLING');
INSERT INTO SKILL(ID,NAME)VALUES(14,'WICKET KEEPING BATTING');


--6. Insert into team
SELECT * FROM TEAM;
INSERT INTO TEAM(ID,NAME,COACH,CAPTIAN,HOME_CITY)VALUES(12347,'DEEPAK HOODA','ABHISHEK BACHAN',12348,12341);
INSERT INTO TEAM(ID,NAME,COACH,CAPTIAN,HOME_CITY)VALUES(12355,'ARJUNDESWAL','RONNIE',12356,12357);


--7. Insert into players
SELECT * FROM PLAYER;
INSERT INTO PLAYER(ID,NAME,COUNTRY,CAPTIAN,SKILL_ID,TEAM_ID)VALUES(12349,'AJINKYAPAWAR','JAIPUR',12350
,12346,12347);
INSERT INTO PLAYER(ID,NAME,COUNTRY,CAPTIAN,SKILL_ID,TEAM_ID)VALUES(12356,'GUMAN SINGH','DELHI',12459,12358,12355);

--8. Insert into venue
SELECT * FROM VENUE;
INSERT INTO VENUE(VENUE_ID,STADIUM_NAME,CITY_ID)VALUES(12351,'Sawai Mansingh Stadium',12341);

--9. Insert into event
SELECT * FROM EVENT;
INSERT INTO EVENT(ID,EVENT_NUMBER,RAID_POINTS,DEFENDING_POINTS ,CLOCK_SECOUNDS,TEAM_ONE_SCORE,TEAM_TWO_SCORE,INNINGS_ID, RAIDER_ID)
VALUES(12352,35,34,12,7,22,31,12343,12349);

--10. Insert into extra_event
SELECT * FROM EXTRA_EVENT;
INSERT INTO EXTRA_EVENT(ID,STADIUM_NAME,POINTS, EVENT_ID,EXTRA_TYPE_ID,SCORING_TEAM_ID)
VALUES(12353,'DEEPAK NIWAS',45,12352,12345,12347);

--11. Insert into outcome
SELECT * FROM OUTCOME;
INSERT INTO OUTCOME(ID,STATUS,SCORE,WINNER_TEAM_ID,PLAYER_OF_MATCH)VALUES(12354, 'GAMEOVER-WINNERTEAM-JAIPUR',38,12347,12349);

--12. Insert into game

--13. Update player table
UPDATE PLAYER
SET COUNTRY = 'INDIA'
WHERE ID=12349;

--14. Update player table
UPDATE PLAYER
SET NAME = 'SANJEEVKUMAR'
WHERE ID=12349;

--15. Update player table
UPDATE PLAYER
SET COUNTRY = 'JAIPUR'
WHERE NAME='SANJEEVKUMAR';

--16. Update player table
UPDATE PLAYER
SET COUNTRY = 'BANGLORE'
WHERE ID=12356;

--17. Delete from extra_type
DELETE FROM EXTRA_TYPE
WHERE ID= 12345;

--18. Delete from referee
DELETE FROM referee
WHERE name='satish';

--19. Delete from player
DELETE FROM PLAYERS
WHERE name='SANJEEVKUMAR';

--20. Delete from outcome

DELETE FROM OUTCOME
WHERE ID=12354;